export const data = [
  {
    "product_category": "phone",
    "product_id": "1",
    "product_title": "Samsung Galaxy S21 Ultra",
    "product_subtitle": "Experience the pinnacle of mobile technology",
    "product_description": "Experience the pinnacle of mobile technology with the Samsung Galaxy S21 Ultra. Featuring a stunning 6.8-inch Dynamic AMOLED display, powerful Snapdragon 888 processor, pro-grade camera system, and 5G connectivity.",
    "product_price": 1199,
    "product_mrp": 1299,
    "product_size": "6.8",
    "product_brand": "Samsung",
    "product_rating": 4.8,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/y/s/l/-original-imagtnqjjuc6dh6v.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/t/3/u/-original-imagt46g4qahyjza.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/u/b/o/-original-imagtnqjmk7dxnkh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/y/g/d/-original-imagtnqjyzabh8wz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/y/g/d/-original-imagtnqjyzabh8wz.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1025
  },
  {
    "product_category": "phone",
    "product_id": "2",
    "product_title": "iPhone 13 Pro Max",
    "product_subtitle": "Unleash your creativity with iPhone 13 Pro Max",
    "product_description": "Unleash your creativity with the iPhone 13 Pro Max. Featuring the most advanced camera system, A15 Bionic chip, ProMotion technology, and stunning design, it's the ultimate tool for capturing and creating.",
    "product_price": 1399,
    "product_mrp": 1499,
    "product_size": "6.7",
    "product_brand": "Apple",
    "product_rating": 4.9,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/ktketu80/mobile/3/e/o/iphone-13-pro-max-mll63hn-a-apple-original-imag6vpgwfgxdsj6.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ktketu80/mobile/j/a/x/iphone-13-pro-mlvv3hn-a-apple-original-imag6vpbngxtrvvx.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ktketu80/mobile/5/v/h/iphone-13-pro-mlvv3hn-a-apple-original-imag6vpbrwudzrng.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/w/k/h/-original-imagh2gwxu57j4fn.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/0/v/-original-imagh7g8urcwshmn.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1368
  },
  {
    "product_category": "phone",
    "product_id": "3",
    "product_title": "Google Pixel 6 Pro",
    "product_subtitle": "Capture every moment with Pixel 6 Pro",
    "product_description": "Capture every moment in stunning detail with the Google Pixel 6 Pro. Featuring a powerful camera system, vibrant OLED display, and Google's latest innovations, it's the ultimate smartphone for photography enthusiasts.",
    "product_price": 1099,
    "product_mrp": 1199,
    "product_size": "6.7",
    "product_brand": "Google",
    "product_rating": 4.7,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/y/e/6/-original-imagtwh4vnkzsrsg.jpeg?q=70&crop=false  ",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/s/u/-original-imagtwh4kdbg5rvr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/k/s/-original-imagtwh46fjzb6fa.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/s/x/-original-imagtwh4snkqfdam.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/h/s/7/-original-imagtwh4m7aygzv3.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 875
  },
  {
    "product_category": "phone",
    "product_id": "4",
    "product_title": "OnePlus 9 Pro",
    "product_subtitle": "Fast and smooth performance",
    "product_description": "Experience fast and smooth performance with the OnePlus 9 Pro. Featuring a Fluid AMOLED display, Hasselblad camera system, Snapdragon 888 processor, and Warp Charge technology, it's designed to elevate your smartphone experience.",
    "product_price": 999,
    "product_mrp": 1099,
    "product_size": "6.7",
    "product_brand": "OnePlus",
    "product_rating": 4.7,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/b/a/a/-original-imaggcee9rkgswbx.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/7/8/x/-original-imaggceesnhp26mv.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/g/u/u/-original-imaggcee6snvwxzf.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/5/l/v/-original-imaggceecp4hgpkv.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/o/i/r/-original-imaggcee7xhqhn6e.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 987
  },
  {
    "product_category": "phone",
    "product_id": "5",
    "product_title": "Xiaomi Mi 11 Ultra",
    "product_subtitle": "Push the boundaries of smartphone photography",
    "product_description": "Push the boundaries of smartphone photography with the Xiaomi Mi 11 Ultra. Featuring a groundbreaking camera system, powerful Snapdragon 888 processor, and stunning 120Hz display, it's the ultimate flagship device.",
    "product_price": 1099,
    "product_mrp": 1199,
    "product_size": "6.81",
    "product_brand": "Xiaomi",
    "product_rating": 4.8,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/kq6yefk0/mobile/i/w/m/11-lite-m2101k9ai-mi-original-imag496gkgqjrvvg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/kq6yefk0/mobile/9/k/a/11-lite-m2101k9ai-mi-original-imag496ggtegxucg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/kq6yefk0/mobile/l/o/y/11-lite-m2101k9ai-mi-original-imag496gydmkfygk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/kq6yefk0/mobile/f/x/f/11-lite-m2101k9ai-mi-original-imag496gbkj5ge2m.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/kq6yefk0/mobile/x/4/s/11-lite-m2101k9ai-mi-original-imag496gdy3qbfbp.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 734
  },
  {
    "product_category": "phone",
    "product_id": "6",
    "product_title": "Sony Xperia 1 III",
    "product_subtitle": "Experience the ultimate cinematic smartphone",
    "product_description": "Experience the ultimate cinematic smartphone with the Sony Xperia 1 III. Featuring a 4K HDR OLED display, triple camera system with ZEISS optics, and pro-level features for creators, it's the perfect companion for multimedia enthusiasts.",
    "product_price": 1299,
    "product_mrp": 1399,
    "product_size": "6.5",
    "product_brand": "Sony",
    "product_rating": 4.6,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/mobile/7/j/a/sony-xperia-c3-original-imadzddjkcztatdz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/mobile/7/j/a/sony-xperia-c3-original-imadzddjkcztatdz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/mobile/7/j/a/sony-xperia-c3-original-imadzddjkcztatdz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/mobile/7/j/a/sony-xperia-c3-original-imadzddjnu4n3shk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/mobile/7/j/a/sony-xperia-c3-original-imadzddjvwwxhgzh.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 605
  },
  {
    "product_category": "phone",
    "product_id": "7",
    "product_title": "Huawei P50 Pro",
    "product_subtitle": "Reinventing smartphone photography",
    "product_description": "Reinventing smartphone photography with the Huawei P50 Pro. Featuring an innovative camera system co-engineered with Leica, powerful Kirin 9000E processor, and sleek design, it sets new standards for mobile imaging.",
    "product_price": 1299,
    "product_mrp": 1399,
    "product_size": "6.6",
    "product_brand": "Huawei",
    "product_rating": 4.7,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/j70sccw0/mobile/z/g/j/honor-8-pro-duke-l09-v100r001-original-imaexdy3pcegz3df.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/j70sccw0/mobile/z/g/j/honor-8-pro-duke-l09-v100r001-original-imaexdy3n5hfpnfx.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/j70sccw0/mobile/z/g/j/honor-8-pro-duke-l09-v100r001-original-imaexdy3bpuduuca.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/j70sccw0/mobile/z/g/j/honor-8-pro-duke-l09-v100r001-original-imaexdy3rhuskzgr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/j70sccw0/mobile/z/g/j/honor-8-pro-duke-l09-v100r001-original-imaexdy34ucztafb.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 508
  },
  {
    "product_category": "phone",
    "product_id": "8",
    "product_title": "Oppo Find X3 Pro",
    "product_subtitle": "Experience true brilliance",
    "product_description": "Experience true brilliance with the Oppo Find X3 Pro. Featuring a Billion Colour QHD+ display, professional-grade camera system with Microlens technology, and flagship performance, it's designed to inspire creativity.",
    "product_price": 1099,
    "product_mrp": 1199,
    "product_size": "6.7",
    "product_brand": "Oppo",
    "product_rating": 4.7,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/3/4/i/-original-imagu8h9snemswmc.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/u/8/x/-original-imagu8h9zrmdf4yr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/u/8/x/-original-imagu8h9zrmdf4yr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/h/w/4/-original-imagu8h99cbzq5nf.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/k/q/p/-original-imagu8h9fdsg43c2.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 376
  },
  {
    "product_category": "phone",
    "product_id": "9",
    "product_title": "Realme GT 5G",
    "product_subtitle": "Power your creativity",
    "product_description": "Power your creativity with the Realme GT 5G. Featuring Snapdragon 888 processor, 120Hz Super AMOLED display, and 65W SuperDart Charge, it's designed to keep up with your fast-paced lifestyle.",
    "product_price": 599,
    "product_mrp": 699,
    "product_size": "6.43",
    "product_brand": "Realme",
    "product_rating": 4.6,
    "product_offer": "15% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/l3rmzrk0/mobile/z/i/t/-original-imagetme2k2rva45.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ksgehzk0/mobile/b/y/g/gt-5g-rmx2202-realme-original-imag6ygfn9fzbzyy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ksgehzk0/mobile/b/y/g/gt-5g-rmx2202-realme-original-imag6ygfn9fzbzyy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ksgehzk0/mobile/e/a/b/gt-5g-rmx2202-realme-original-imag6ygfgqsamkfg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ksgehzk0/mobile/y/x/9/gt-5g-rmx2202-realme-original-imag6ygftfqwgqd4.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 256
  },
  {
    "product_category": "phone",
    "product_id": "10",
    "product_title": "Vivo X60 Pro+",
    "product_subtitle": "Capture the moment, light up your life",
    "product_description": "Capture the moment and light up your life with the Vivo X60 Pro+. Featuring a professional photography system co-engineered with ZEISS, Snapdragon 888 processor, and sleek design, it's the perfect blend of style and performance.",
    "product_price": 999,
    "product_mrp": 1099,
    "product_size": "6.56",
    "product_brand": "Vivo",
    "product_rating": 4.6,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/kmns7m80/mobile/r/a/f/x60-pro-v2047-vivo-original-imagfht6cwsabkhg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/kmns7m80/mobile/r/a/f/x60-pro-v2047-vivo-original-imagfht6cwsabkhg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/kmns7m80/mobile/r/e/c/x60-pro-v2047-vivo-original-imagfht66mkfmsny.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/kmns7m80/mobile/4/b/q/x60-pro-v2047-vivo-original-imagfht6jjgz7qaf.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/kmns7m80/mobile/4/b/q/x60-pro-v2047-vivo-original-imagfht6jjgz7qaf.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 420
  },
  {
    "product_category": "phone",
    "product_id": "11",
    "product_title": "Motorola Edge 20 Pro",
    "product_subtitle": "Elevate your mobile photography",
    "product_description": "Elevate your mobile photography with the Motorola Edge 20 Pro. Featuring a 108MP triple camera system, Snapdragon 870 processor, and 144Hz AMOLED display, it's designed to capture every detail with precision.",
    "product_price": 899,
    "product_mrp": 999,
    "product_size": "6.7",
    "product_brand": "Motorola",
    "product_rating": 4.5,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/ku5ufm80/mobile/q/s/c/edge-20-pro-pany0009in-motorola-original-imag7csrdfzh6eqh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ku5ufm80/mobile/e/d/x/edge-20-pro-pany0009in-motorola-original-imag7csr6xah4zet.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ku5ufm80/mobile/f/l/y/edge-20-pro-pany0009in-motorola-original-imag7csrsjbbxaf5.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ku5ufm80/mobile/f/l/y/edge-20-pro-pany0009in-motorola-original-imag7csrsjbbxaf5.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ku5ufm80/mobile/f/l/y/edge-20-pro-pany0009in-motorola-original-imag7csrsjbbxaf5.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 328
  },
  {
    "product_category": "phone",
    "product_id": "12",
    "product_title": "Asus ROG Phone 5",
    "product_subtitle": "Dominate the game",
    "product_description": "Dominate the game with the Asus ROG Phone 5. Featuring Snapdragon 888 processor, 144Hz AMOLED display, and advanced gaming features, it's designed to take your mobile gaming experience to the next level.",
    "product_price": 1099,
    "product_mrp": 1199,
    "product_size": "6.78",
    "product_brand": "Asus",
    "product_rating": 4.8,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/ky7lci80/mobile/t/x/j/-original-imagahvge92r5fmm.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ky7lci80/mobile/4/f/b/-original-imagahvgf5gzt6sz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ky7lci80/mobile/m/k/z/-original-imagahvgdm4ycnam.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ky7lci80/mobile/m/l/c/-original-imagahvgdvs4gzrq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/ky7lci80/mobile/r/d/j/-original-imagahvg3p5g9hwh.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 512
  },
  {
    "product_category": "phone",
    "product_id": "13",
    "product_title": "LG Wing",
    "product_subtitle": "Experience the swivel design",
    "product_description": "Experience the swivel design with the LG Wing. Featuring a unique dual-screen design, Gimbal Motion Camera, and Snapdragon 765G processor, it's designed to enhance your multitasking and creativity.",
    "product_price": 799,
    "product_mrp": 899,
    "product_size": "6.8-inch display",
    "product_brand": "LG",
    "product_rating": 4.5,
    "product_offer": "10% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/416/416/khtghow0/mobile/m/s/y/lg-wing-lmf100emw-original-imafxqsrfvkexbr6.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/khtghow0/mobile/m/s/y/lg-wing-lmf100emw-original-imafxqsrfvkexbr6.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/khxqt8w0/mobile/m/s/y/lg-wing-lmf100emw-original-imafxu2zsx3yzceh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/kingqkw0/mobile/m/s/y/lg-wing-lmf100emw-original-imafyefkxvfppvgn.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/416/416/khtghow0/mobile/m/s/y/lg-wing-lmf100emw-original-imafxqsrg7kar6c5.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 289
  },

  {
    "product_category": "clothes",
    "product_id": "14",
    "product_title": "Levi's 501 Original Fit Jeans",
    "product_subtitle": "Timeless style and comfort",
    "product_description": "Experience timeless style and comfort with Levi's 501 Original Fit Jeans. Crafted from premium denim, these jeans feature a classic straight-leg silhouette and iconic Levi's detailing.",
    "product_price": 59,
    "product_mrp": 79,
    "product_size": "M",
    "product_brand": "Levi's",
    "product_rating": 4.8,
    "product_offer": "25% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/t/h/1/32-18298-1268-levi-s-original-imaget8jrfzwqhrw-bb.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l3rmzrk0/jean/j/k/5/32-18298-1268-levi-s-original-imaget8jhp3gatgg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l3rmzrk0/jean/b/k/l/32-18298-1268-levi-s-original-imaget8jaqdhxupk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l3rmzrk0/jean/b/l/q/32-18298-1268-levi-s-original-imaget8j8jmwu4xd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l3rmzrk0/jean/b/l/q/32-18298-1268-levi-s-original-imaget8j8jmwu4xd.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1056
  },
  {
    "product_category": "clothes",
    "product_id": "15",
    "product_title": "Nike Sportswear Club Fleece Hoodie",
    "product_subtitle": "Stay cozy and stylish",
    "product_description": "Stay cozy and stylish with the Nike Sportswear Club Fleece Hoodie. Made from soft fleece fabric, this hoodie offers warmth and comfort, perfect for everyday wear.",
    "product_price": 39,
    "product_mrp": 49,
    "product_size": "L",
    "product_brand": "Nike",
    "product_rating": 4.7,
    "product_offer": "20% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/s/9/k/l-bul-s23bw-01c-bullmer-original-imagsuqg7bwtankz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/t/l/4/l-bul-s23bw-01c-bullmer-original-imagsuqgsh4v4j2u.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/d/r/b/l-bul-s23bw-01c-bullmer-original-imagsuqgpzskftp7.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/9/j/e/l-bul-s23bw-01c-bullmer-original-imagsuqgqkwhhfuu.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/m/b/g/l-bul-s23bw-01c-bullmer-original-imagsuqgq6e7krez.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 892
  },
  {
    "product_category": "clothes",
    "product_id": "16",
    "product_title": "Adidas Essentials 3-Stripes Pants",
    "product_subtitle": "Versatile and comfortable",
    "product_description": "Stay comfortable on the go with Adidas Essentials 3-Stripes Pants. These pants feature a classic design with signature 3-Stripes detailing, making them perfect for workouts or casual wear.",
    "product_price": 34,
    "product_mrp": 44,
    "product_size": "S",
    "product_brand": "Adidas",
    "product_rating": 4.6,
    "product_offer": "20% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/track-pant/h/n/9/m-hz8947-adidas-original-imaguywaes9hbcua.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/track-pant/a/r/y/m-hz8947-adidas-original-imaguywayyejuz76.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/track-pant/a/r/y/m-hz8947-adidas-original-imaguywayyejuz76.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/track-pant/a/r/y/m-hz8947-adidas-original-imaguywayyejuz76.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/track-pant/b/h/x/m-hz8947-adidas-original-imaguywasbecxzdu.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 734
  },
  {
    "product_category": "clothes",
    "product_id": "17",
    "product_title": "Under Armour Tech 2.0 T-Shirt",
    "product_subtitle": "Stay dry and comfortable",
    "product_description": "Stay dry and comfortable during workouts with the Under Armour Tech 2.0 T-Shirt. Made from UA Tech fabric, this t-shirt wicks away sweat and dries quickly, keeping you focused on your training.",
    "product_price": 24,
    "product_mrp": 34,
    "product_size": "M",
    "product_brand": "Under Armour",
    "product_rating": 4.5,
    "product_offer": "30% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/z/1/h/-original-imagubhz7tuwdmxz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/m/j/e/-original-imagubhzhcxhvt7e.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/b/f/u/-original-imagubhzyeems42e.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/w/m/q/-original-imagubhzh4wbrjye.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/c/n/b/-original-imagubhzbc5u52as.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 609
  },
  {
    "product_category": "clothes",
    "product_id": "18",
    "product_title": "The North Face Resolve 2 Jacket",
    "product_subtitle": "Stay dry in wet conditions",
    "product_description": "Stay dry in wet conditions with The North Face Resolve 2 Jacket. Featuring DryVent technology, this waterproof jacket offers breathable protection from rain and wind, making it ideal for outdoor adventures.",
    "product_price": 89,
    "product_mrp": 109,
    "product_size": "XL",
    "product_brand": "The North Face",
    "product_rating": 4.8,
    "product_offer": "20% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/p/g/l/xl-12288646-roadster-original-imafyurmnd9mtbyz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/d/y/s/xl-12288646-roadster-original-imafyurmpygpp4gd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/m/e/x/xl-12288646-roadster-original-imafyurmxsphpfuy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/g/u/c/xl-12288646-roadster-original-imafyurmge9zrhyg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/g/u/c/xl-12288646-roadster-original-imafyurmge9zrhyg.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 512
  },
  {
    "product_category": "clothes",
    "product_id": "19",
    "product_title": "H&M Slim Fit Chinos",
    "product_subtitle": "Classic style for any occasion",
    "product_description": "Achieve a classic and polished look with H&M Slim Fit Chinos. Made from stretch cotton twill, these chinos offer a comfortable fit and versatile style that's perfect for any occasion.",
    "product_price": 29,
    "product_mrp": 39,
    "product_size": "M",
    "product_brand": "H&M",
    "product_rating": 4.6,
    "product_offer": "25% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/l2rwzgw0/trouser/m/w/d/38-b101-brown-dennis-lingo-original-imagefctvmjgfs26.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l2rwzgw0/trouser/6/d/n/38-b101-brown-dennis-lingo-original-imagefctvdknqv6a.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l2rwzgw0/trouser/n/a/5/38-b101-brown-dennis-lingo-original-imagefctpsncrgwn.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l2rwzgw0/trouser/n/g/0/38-b101-brown-dennis-lingo-original-imagefctv5uh2etr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l2rwzgw0/trouser/r/0/e/38-b101-brown-dennis-lingo-original-imagefctpfjhcyrj.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 420
  },
  {
    "product_category": "clothes",
    "product_id": "20",
    "product_title": "Men Night Suit Set Multicolor Printed",
    "product_subtitle": "Ultimate comfort and support",
    "product_description": "Experience ultimate comfort and support with the Calvin Klein Made from soft and breathable cotton.",
    "product_price": 34,
    "product_mrp": 49,
    "product_size": "L",
    "product_brand": "Calvin Klein",
    "product_rating": 4.7,
    "product_offer": "30% off",
    "product_discount": 15,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/night-suit/s/e/l/xxl-zara-lg-fashion-original-imagpa5f5b6bau4e.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/night-suit/0/y/s/xxl-zara-lg-fashion-original-imagpa5f76ptzqhk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/night-suit/w/g/p/xxl-zara-lg-fashion-original-imagpa5fuyynqhnr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/night-suit/e/8/7/xxl-zara-lg-fashion-original-imagpa5fnzyvvwnv.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/night-suit/w/g/p/xxl-zara-lg-fashion-original-imagpa5fuyynqhnr.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 876
  },
  {
    "product_category": "clothes",
    "product_id": "21",
    "product_title": "Tommy Hilfiger Classic T-Shirt",
    "product_subtitle": "Iconic style and comfort",
    "product_description": "Achieve iconic style and comfort with the Tommy Hilfiger Classic T-Shirt. Made from soft cotton jersey, this t-shirt features the signature Tommy Hilfiger flag logo for a timeless look.",
    "product_price": 24,
    "product_mrp": 34,
    "product_size": "M",
    "product_brand": "Tommy Hilfiger",
    "product_rating": 4.8,
    "product_offer": "20% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/q/3/6/m-s23hmkt017-tommy-hilfiger-original-imagz3pgz5jhhd3f.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/q/3/6/m-s23hmkt017-tommy-hilfiger-original-imagz3pgz5jhhd3f.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/q/3/6/m-s23hmkt017-tommy-hilfiger-original-imagz3pgz5jhhd3f.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/q/y/6/m-s23hmkt017-tommy-hilfiger-original-imagz3pg4cuashvb.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/q/y/6/m-s23hmkt017-tommy-hilfiger-original-imagz3pg4cuashvb.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 735
  },
  {
    "product_category": "clothes",
    "product_id": "22",
    "product_title": "Ralph Lauren Polo Shirt",
    "product_subtitle": "Timeless elegance and comfort",
    "product_description": "Experience timeless elegance and comfort with the Ralph Lauren Polo Shirt. Crafted from soft cotton piqué, this shirt features the iconic Polo Pony logo and classic fit for a polished look.",
    "product_price": 49,
    "product_mrp": 69,
    "product_size": "L",
    "product_brand": "Ralph Lauren",
    "product_rating": 4.7,
    "product_offer": "30% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/p/0/x/m-001-burrmallow-original-imagpngt48buagjp.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/p/0/x/m-001-burrmallow-original-imagpngt48buagjp.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/o/q/6/xl-sht02-ethvil-original-imagruyhuwvzvn4c.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/o/q/6/xl-sht02-ethvil-original-imagruyhuwvzvn4c.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/o/q/6/xl-sht02-ethvil-original-imagruyhuwvzvn4c.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 987
  },
  {
    "product_category": "clothes",
    "product_id": "23",
    "product_title": "GAP 1969 Denim Jacket",
    "product_subtitle": "Timeless style for any season",
    "product_description": "Achieve timeless style for any season with the GAP 1969 Denim Jacket. Made from premium denim, this jacket features a classic trucker silhouette and distressed detailing for a worn-in look.",
    "product_price": 69,
    "product_mrp": 89,
    "product_size": "XL",
    "product_brand": "GAP",
    "product_rating": 4.6,
    "product_offer": "20% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/s/8/j/xxl-12288668-roadster-original-imafyurz9ufgfz5h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/0/p/e/xxl-12288668-roadster-original-imafyurzyjjdq9cp.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/z/e/r/xxl-12288668-roadster-original-imafyurzhqdchd3b.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/z/e/r/xxl-12288668-roadster-original-imafyurzhqdchd3b.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kj8wccw0-0/jacket/6/p/a/xxl-12288668-roadster-original-imafyurzfa68h56a.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 892
  },
  {
    "product_category": "clothes",
    "product_id": "24",
    "product_title": "Zara Basic Slim Fit Trousers",
    "product_subtitle": "Versatile style for modern wardrobes",
    "product_description": "Add versatile style to your modern wardrobe with Zara Basic Slim Fit Trousers. Made from stretch fabric, these trousers offer a comfortable fit and contemporary silhouette, perfect for work or weekends.",
    "product_price": 39,
    "product_mrp": 49,
    "product_size": "M",
    "product_brand": "Zara",
    "product_rating": 4.7,
    "product_offer": "20% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/j/z/k/xl-ussht1669-u-s-polo-assn-original-imagsurrftte6dyz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/j/z/k/xl-ussht1669-u-s-polo-assn-original-imagsurrftte6dyz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/q/y/d/xl-ussht1669-u-s-polo-assn-original-imagsurrfh6p3g5r.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/e/u/7/xl-ussht1669-u-s-polo-assn-original-imagsurrbnbwawrp.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/q/a/8/xl-ussht1669-u-s-polo-assn-original-imagsurrzhrsq2en.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1098
  },
  {
    "product_category": "clothes",
    "product_id": "25",
    "product_title": "Uniqlo Heattech Crewneck Sweater",
    "product_subtitle": "Stay warm and stylish",
    "product_description": "Stay warm and stylish during colder months with Uniqlo Heattech Crewneck Sweater. Made from innovative Heattech fabric, this sweater retains heat while wicking away moisture, keeping you comfortable all day long.",
    "product_price": 29,
    "product_mrp": 39,
    "product_size": "L",
    "product_brand": "Uniqlo",
    "product_rating": 4.6,
    "product_offer": "25% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweater/j/9/f/l-asaesw4218-arrow-sport-original-imagg6gkbdsk8htd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweater/j/9/f/l-asaesw4218-arrow-sport-original-imagg6gkbdsk8htd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweater/j/9/f/l-asaesw4218-arrow-sport-original-imagg6gkbdsk8htd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweater/j/9/f/l-asaesw4218-arrow-sport-original-imagg6gkbdsk8htd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweater/j/9/f/l-asaesw4218-arrow-sport-original-imagg6gkbdsk8htd.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 786
  },
  {
    "product_category": "clothes",
    "product_id": "26",
    "product_title": "Hollister Co. Classic Logo Hoodie",
    "product_subtitle": "Casual comfort with signature style",
    "product_description": "Experience casual comfort with signature style in the Hollister Co. Classic Logo Hoodie. Made from soft fleece fabric, this hoodie features the iconic Hollister logo and kangaroo pocket for laid-back vibes.",
    "product_price": 49,
    "product_mrp": 69,
    "product_size": "XL",
    "product_brand": "Hollister Co.",
    "product_rating": 4.5,
    "product_offer": "30% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/m/m/j/xxl-alstargft34812-allen-solly-original-imagvfnhkzmxnvbh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/a/k/s/xxl-alstargft34812-allen-solly-original-imagvfnhbctht48g.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/a/k/s/xxl-alstargft34812-allen-solly-original-imagvfnhbctht48g.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/l/b/s/xxl-alstargft34812-allen-solly-original-imagvfnhnvb7mzts.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/sweatshirt/j/p/x/xxl-alstargft34812-allen-solly-original-imagvfnhhzr5p4hw.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 654
  },

  {
    "product_category": "shoes",
    "product_id": "27",
    "product_title": "Nike Air Force 1",
    "product_subtitle": "Classic style meets modern comfort",
    "product_description": "Experience classic style and modern comfort with the Nike Air Force 1. Featuring a timeless design, premium leather upper, and Nike Air cushioning, these shoes provide all-day comfort and style.",
    "product_price": 89,
    "product_mrp": 99,
    "product_size": "US 9",
    "product_brand": "Nike",
    "product_rating": 4.8,
    "product_offer": "10% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/l/f/a/-original-imagx8gvt9q9uy2p.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/9/k/i/-original-imagpgpes3mxzbgc.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/r/t/-original-imagpgpescghezh6.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/r/t/-original-imagpgpescghezh6.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/k/g/s/-original-imagpgpehyugbmj6.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1345
  },
  {
    "product_category": "shoes",
    "product_id": "28",
    "product_title": "Adidas Ultraboost 21",
    "product_subtitle": "Unleash your energy with every step",
    "product_description": "Unleash your energy with every step in the Adidas Ultraboost 21. Featuring Boost cushioning, Primeknit upper, and Stretchweb outsole, these shoes deliver unparalleled comfort and responsiveness.",
    "product_price": 129,
    "product_mrp": 149,
    "product_size": "US 10",
    "product_brand": "Adidas",
    "product_rating": 4.9,
    "product_offer": "13% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/r/s/e/-original-imagnre4dqgggvfg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/r/s/e/-original-imagnre4dqgggvfg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/r/s/e/-original-imagnre4dqgggvfg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/r/s/e/-original-imagnre4dqgggvfg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/y/s/q/-original-imagnre4t9zvqamt.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 998
  },
  {
    "product_category": "shoes",
    "product_id": "29",
    "product_title": "Converse Chuck Taylor All Star",
    "product_subtitle": "Iconic style for every day",
    "product_description": "Rock iconic style every day with the Converse Chuck Taylor All Star. Featuring a canvas upper, classic silhouette, and vulcanized rubber sole, these sneakers are a timeless wardrobe staple.",
    "product_price": 49,
    "product_mrp": 59,
    "product_size": "US 8",
    "product_brand": "Converse",
    "product_rating": 4.7,
    "product_offer": "16% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/o/l/9-wk-562-red-woakers-red-original-imagznw7frbqskkg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/o/l/9-wk-562-red-woakers-red-original-imagznw7frbqskkg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/o/l/9-wk-562-red-woakers-red-original-imagznw7frbqskkg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/o/l/9-wk-562-red-woakers-red-original-imagznw7frbqskkg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/o/l/9-wk-562-red-woakers-red-original-imagznw7frbqskkg.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 756
  },
  {
    "product_category": "shoes",
    "product_id": "30",
    "product_title": "Puma Future Rider",
    "product_subtitle": "Retro style meets modern comfort",
    "product_description": "Experience retro style with modern comfort in the Puma Future Rider. Featuring a nylon upper, IMEVA midsole, and rubber outsole, these sneakers offer lightweight cushioning and traction.",
    "product_price": 69,
    "product_mrp": 79,
    "product_size": "US 9.5",
    "product_brand": "Puma",
    "product_rating": 4.6,
    "product_offer": "12% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/r/x/y/6-391927-6-puma-white-bright-melon-original-imaguwbhghb3rhjc.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/s/i/6-391927-6-puma-white-bright-melon-original-imaguwbhuehcqjhe.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/p/v/8/6-391927-6-puma-white-bright-melon-original-imaguwbhj4xehhxw.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/g/q/v/6-391927-6-puma-white-bright-melon-original-imaguwbhncjtkdtg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/g/q/v/6-391927-6-puma-white-bright-melon-original-imaguwbhncjtkdtg.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 609
  },
  {
    "product_category": "shoes",
    "product_id": "31",
    "product_title": "New Balance 574",
    "product_subtitle": "Heritage style with modern comfort",
    "product_description": "Blend heritage style with modern comfort in the New Balance 574. Featuring a suede and mesh upper, ENCAP midsole, and rubber outsole, these sneakers offer superior cushioning and durability.",
    "product_price": 79,
    "product_mrp": 89,
    "product_size": "US 10.5",
    "product_brand": "New Balance",
    "product_rating": 4.8,
    "product_offer": "11% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/k/u/l/9-jr-1-airson-cl-aqua-org-original-imagy2rgecnawerz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/k/u/l/9-jr-1-airson-cl-aqua-org-original-imagy2rgecnawerz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/k/u/l/9-jr-1-airson-cl-aqua-org-original-imagy2rgecnawerz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/k/u/l/9-jr-1-airson-cl-aqua-org-original-imagy2rgecnawerz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/k/u/l/9-jr-1-airson-cl-aqua-org-original-imagy2rgecnawerz.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 734
  },
  {
    "product_category": "shoes",
    "product_id": "32",
    "product_title": "Reebok Classic Leather",
    "product_subtitle": "Timeless design for everyday wear",
    "product_description": "Embrace timeless design for everyday wear in the Reebok Classic Leather. Featuring a soft leather upper, EVA midsole, and high-abrasion rubber outsole, these sneakers offer comfort and durability.",
    "product_price": 64,
    "product_mrp": 74,
    "product_size": "US 9.5",
    "product_brand": "Reebok",
    "product_rating": 4.7,
    "product_offer": "13% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/e/t/h/-original-imagz4pgn7baympw.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/z/g/g/-original-imagz4pguj8z9kx8.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/8/z/u/-original-imagudcfpvxezpz4.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/8/z/u/-original-imagudcfpvxezpz4.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/b/7/s/-original-imagz4pghtfufpyg.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 888
  },
  {
    "product_category": "shoes",
    "product_id": "33",
    "product_title": "Vans Old Skool",
    "product_subtitle": "Classic skate style for every day",
    "product_description": "Rock classic skate style every day in the Vans Old Skool. Featuring a canvas and suede upper, padded collar, and signature waffle outsole, these sneakers offer comfort and durability.",
    "product_price": 59,
    "product_mrp": 69,
    "product_size": "US 10",
    "product_brand": "Vans",
    "product_rating": 4.8,
    "product_offer": "14% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/kzsqykw0/shoe/2/v/b/10-9413-world-wear-footwear-grey-original-imagbqyjzjzuvfwb.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kzsqykw0/shoe/2/v/b/10-9413-world-wear-footwear-grey-original-imagbqyjzjzuvfwb.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kzsqykw0/shoe/2/v/b/10-9413-world-wear-footwear-grey-original-imagbqyjzjzuvfwb.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kzsqykw0/shoe/h/r/t/9-9413-camfoot-grey-orange-original-imagbq3tby5du3hh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kzsqykw0/shoe/h/y/q/9-9413-camfoot-grey-orange-original-imagbq3tx2awjzt4.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1001
  },
  {
    "product_category": "shoes",
    "product_id": "34",
    "product_title": "Timberland 6-Inch Premium Boots",
    "product_subtitle": "Iconic style for outdoor adventures",
    "product_description": "Step into iconic style for outdoor adventures with the Timberland 6-Inch Premium Boots. Featuring a waterproof leather upper, padded collar, and durable rubber outsole, these boots are built to last.",
    "product_price": 149,
    "product_mrp": 169,
    "product_size": "US 11",
    "product_brand": "Timberland",
    "product_rating": 4.9,
    "product_offer": "12% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/ku79vgw0/shoe/p/0/g/8-bbma2178-bacca-bucci-black-original-imag7dmfum74zff8.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/ku79vgw0/shoe/p/0/g/8-bbma2178-bacca-bucci-black-original-imag7dmfum74zff8.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/ku79vgw0/shoe/p/0/g/8-bbma2178-bacca-bucci-black-original-imag7dmfum74zff8.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/ku79vgw0/shoe/p/l/m/8-bbma2178-bacca-bucci-black-original-imag7dmfncqpfdhr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/ku79vgw0/shoe/p/l/m/8-bbma2178-bacca-bucci-black-original-imag7dmfncqpfdhr.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 876
  },
  {
    "product_category": "shoes",
    "product_id": "35",
    "product_title": "Dr. Martens 1460 Boots",
    "product_subtitle": "Timeless style for rebellious spirits",
    "product_description": "Express your rebellious spirit with timeless style in the Dr. Martens 1460 Boots. Featuring a smooth leather upper, air-cushioned sole, and iconic yellow stitching, these boots are an essential addition to your wardrobe.",
    "product_price": 139,
    "product_mrp": 159,
    "product_size": "US 10",
    "product_brand": "Dr. Martens",
    "product_rating": 4.7,
    "product_offer": "12% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/u/u/r/6-g-1101-stl-zixer-lite-grey-original-imagqg8gcgpphhbd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/u/u/r/6-g-1101-stl-zixer-lite-grey-original-imagqg8gcgpphhbd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/5/2/v/6-g-1101-stl-zixer-lite-grey-original-imagqg8g4tzxardx.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/5/2/v/6-g-1101-stl-zixer-lite-grey-original-imagqg8g4tzxardx.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/f/c/p/6-g-1101-stl-zixer-lite-grey-original-imagqg8gxmzjgzu6.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 734
  },
  {
    "product_category": "shoes",
    "product_id": "36",
    "product_title": "Skechers Go Walk 5",
    "product_subtitle": "Ultimate comfort for daily walks",
    "product_description": "Experience ultimate comfort for daily walks in the Skechers Go Walk 5. Featuring lightweight and responsive ULTRA GO cushioning, breathable mesh upper, and high-rebound COMFORT PILLAR TECHNOLOGY, these shoes provide unmatched comfort and support.",
    "product_price": 49,
    "product_mrp": 59,
    "product_size": "US 9",
    "product_brand": "Skechers",
    "product_rating": 4.6,
    "product_offer": "16% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/v/u/w/3-15952-6-skechers-yel-original-imagz3srmjcygw6h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/v/u/w/3-15952-6-skechers-yel-original-imagz3srmjcygw6h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/v/u/w/3-15952-6-skechers-yel-original-imagz3srmjcygw6h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/v/u/w/3-15952-6-skechers-yel-original-imagz3srmjcygw6h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/v/u/w/3-15952-6-skechers-yel-original-imagz3srmjcygw6h.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 609
  },
  {
    "product_category": "shoes",
    "product_id": "37",
    "product_title": "Fila Disruptor II",
    "product_subtitle": "Bold style for trendsetters",
    "product_description": "Make a bold statement with trendsetting style in the Fila Disruptor II. Featuring a leather and synthetic upper, chunky silhouette, and EVA midsole, these sneakers offer retro-inspired style and all-day comfort.",
    "product_price": 79,
    "product_mrp": 89,
    "product_size": "US 10",
    "product_brand": "Fila",
    "product_rating": 4.7,
    "product_offer": "11% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/w/u/f/10-500-corsac-black-original-imagt84fhskjasjp.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/w/u/f/10-500-corsac-black-original-imagt84fhskjasjp.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/w/u/f/10-500-corsac-black-original-imagt84fhskjasjp.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/y/r/5/10-500-corsac-black-original-imagt84fhwmgppgb.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/g/a/10-500-corsac-black-original-imagt84fyzfqzqzz.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 888
  },
  {
    "product_category": "shoes",
    "product_id": "38",
    "product_title": "Vans Authentic",
    "product_subtitle": "Classic style for every day",
    "product_description": "Rock classic style every day with the Vans Authentic. Featuring a canvas upper, metal eyelets, and signature rubber waffle outsole, these sneakers are a timeless wardrobe staple.",
    "product_price": 54,
    "product_mrp": 64,
    "product_size": "US 9.5",
    "product_brand": "Vans",
    "product_rating": 4.8,
    "product_offer": "15% off",
    "product_discount": 10,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/h/q/a/11-na-vhscgrgawl00016-45-van-heusen-brown-original-imagzjezktasxqhq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/h/q/a/11-na-vhscgrgawl00016-45-van-heusen-brown-original-imagzjezktasxqhq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/u/g/y/11-na-vhscgrgawl00016-45-van-heusen-brown-original-imagzjezemaspw8z.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/u/g/y/11-na-vhscgrgawl00016-45-van-heusen-brown-original-imagzjezemaspw8z.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/g/k/r/11-na-vhscgrgawl00016-45-van-heusen-brown-original-imagzjezp3ncnbnc.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1001
  },
  {
    "product_category": "shoes",
    "product_id": "39",
    "product_title": "ASICS Gel-Kayano 27",
    "product_subtitle": "Unmatched stability and comfort",
    "product_description": "Experience unmatched stability and comfort in the ASICS Gel-Kayano 27. Featuring FlyteFoam Propel technology, GEL cushioning, and DUOMAX midsole, these running shoes provide exceptional support and cushioning mile after mile.",
    "product_price": 149,
    "product_mrp": 169,
    "product_size": "US 10",
    "product_brand": "ASICS",
    "product_rating": 4.9,
    "product_offer": "12% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/kqpj4i80/shoe/o/q/k/7-1011b189-002-asics-black-electric-red-original-imag4z6hrfyyrrbk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kqpj4i80/shoe/o/4/i/7-1011b189-002-asics-black-electric-red-original-imag4z6hagzwhmgk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/x/s/2/-original-imagg3fnvxda4vse.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kqpj4i80/shoe/g/9/b/7-1011b189-002-asics-black-electric-red-original-imag4z6hgwfbzzmv.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kqpj4i80/shoe/j/a/1/7-1011b189-002-asics-black-electric-red-original-imag4z6hfngqffwe.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 876
  },
  {
    "product_category": "watch",
    "product_id": "40",
    "product_title": "Rolex Submariner",
    "product_subtitle": "Iconic dive watch for adventurers",
    "product_description": "Discover the iconic Rolex Submariner, a legendary dive watch designed for adventurers. Featuring a stainless steel case, ceramic bezel, and automatic movement, this watch offers precision and reliability both underwater and on land.",
    "product_price": 9999,
    "product_mrp": 10999,
    "product_size": "42mm",
    "product_brand": "Rolex",
    "product_rating": 4.9,
    "product_offer": "9% off",
    "product_discount": 1000,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/u/q/y/1-bp3127x-390-beverly-hills-polo-club-men-original-imagwrw4azbzg3qy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/c/p/m/1-bp3127x-390-beverly-hills-polo-club-men-original-imagwrw4qu7udunh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/c/p/m/1-bp3127x-390-beverly-hills-polo-club-men-original-imagwrw4qu7udunh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/c/p/m/1-bp3127x-390-beverly-hills-polo-club-men-original-imagwrw4qu7udunh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/c/p/m/1-bp3127x-390-beverly-hills-polo-club-men-original-imagwrw4qu7udunh.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 2045
  },
  {
    "product_category": "watch",
    "product_id": "41",
    "product_title": "Omega Speedmaster Professional Moonwatch",
    "product_subtitle": "Legendary timepiece for space enthusiasts",
    "product_description": "Own a piece of history with the Omega Speedmaster Professional Moonwatch. Worn by astronauts during the Apollo missions, this legendary timepiece features a stainless steel case, manual-winding movement, and iconic chronograph function.",
    "product_price": 5499,
    "product_mrp": 5999,
    "product_size": "42mm",
    "product_brand": "Omega",
    "product_rating": 4.8,
    "product_offer": "8% off",
    "product_discount": 500,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/k4rcmfk0pkrrdj/watch-refurbished/q/5/6/c-68007pp02-fastrack-original-imafcg3zfyzuqrtz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/k4rcmfk0pkrrdj/watch-refurbished/q/5/6/c-68007pp02-fastrack-original-imafcg3zfyzuqrtz.jpeg?q=70&crop=false  ",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/i/j/i/-original-imagrzsxgxnf4mxa.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/k4rcmfk0pkrrdj/watch-refurbished/q/5/6/c-68007pp02-fastrack-original-imafcg3zdghnm8pv.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l01blow0/watch/z/3/l/-original-imagbwyyckgkybuw.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1789
  },
  {
    "product_category": "watch",
    "product_id": "42",
    "product_title": "TAG Heuer Carrera",
    "product_subtitle": "Sporty elegance for modern professionals",
    "product_description": "Experience sporty elegance with the TAG Heuer Carrera. Featuring a stainless steel case, sapphire crystal, and Swiss automatic movement, this watch combines timeless style with precision engineering.",
    "product_price": 3899,
    "product_mrp": 4299,
    "product_size": "40mm",
    "product_brand": "TAG Heuer",
    "product_rating": 4.7,
    "product_offer": "9% off",
    "product_discount": 400,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/l4d2ljk0/watch/n/x/y/1-fs4656-fossil-men-original-imagfa4n7dc8ws2p.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l4d2ljk0/watch/n/x/y/1-fs4656-fossil-men-original-imagfa4n7dc8ws2p.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/y/n/y/-original-imagpb4zshyrafvj.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l4d2ljk0/watch/t/z/d/1-fs4656-fossil-men-original-imagfa4nqyzpghpq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l4d2ljk0/watch/t/z/z/1-fs4656-fossil-men-original-imagfa4ndpyggppg.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1256
  },
  {
    "product_category": "watch",
    "product_id": "43",
    "product_title": "Seiko SKX007",
    "product_subtitle": "Legendary dive watch for enthusiasts",
    "product_description": "Embrace legendary dive watch heritage with the Seiko SKX007. Featuring a stainless steel case, unidirectional bezel, and automatic movement, this watch offers robust performance and timeless style.",
    "product_price": 299,
    "product_mrp": 349,
    "product_size": "42mm",
    "product_brand": "Seiko",
    "product_rating": 4.6,
    "product_offer": "14% off",
    "product_discount": 50,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/l4d2ljk0/watch/t/z/z/1-fs4656-fossil-men-original-imagfa4ndpyggppg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l4d2ljk0/watch/t/z/z/1-fs4656-fossil-men-original-imagfa4ndpyggppg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/z/l/0/-original-imagt7fhq8fwjgnr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kk76wsw0/watch/w/3/g/ar1970-emporio-armani-original-imafzh9zq7ej9dva.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kk76wsw0/watch/e/c/a/ar1970-emporio-armani-original-imafzh9zfhfajdd8.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 983
  },
  {
    "product_category": "watch",
    "product_id": "44",
    "product_title": "Tissot Le Locle",
    "product_subtitle": "Elegant Swiss watchmaking",
    "product_description": "Experience elegant Swiss watchmaking with the Tissot Le Locle. Featuring a stainless steel case, sapphire crystal, and automatic movement, this watch exemplifies timeless sophistication.",
    "product_price": 599,
    "product_mrp": 649,
    "product_size": "39mm",
    "product_brand": "Tissot",
    "product_rating": 4.7,
    "product_offer": "8% off",
    "product_discount": 50,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/1/i/k/-original-imagnu3ndz5mjx6a.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/1/i/k/-original-imagnu3ndz5mjx6a.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/1/i/k/-original-imagnu3ndz5mjx6a.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/1/i/k/-original-imagnu3ndz5mjx6a.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/1/i/k/-original-imagnu3ndz5mjx6a.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1101
  },
  {
    "product_category": "watch",
    "product_id": "45",
    "product_title": "Citizen Eco-Drive Promaster Diver",
    "product_subtitle": "Solar-powered dive watch for adventurers",
    "product_description": "Explore the depths with the Citizen Eco-Drive Promaster Diver. Powered by light, this dive watch features a stainless steel case, unidirectional bezel, and Eco-Drive technology for reliable performance underwater.",
    "product_price": 249,
    "product_mrp": 299,
    "product_size": "44mm",
    "product_brand": "Citizen",
    "product_rating": 4.8,
    "product_offer": "17% off",
    "product_discount": 50,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/q/h/x/-original-imagsaxmubhkvhbh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/h/e/j/-original-imagsaxm9ezw5xgx.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/h/e/j/-original-imagsaxm9ezw5xgx.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/h/e/j/-original-imagsaxm9ezw5xgx.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/g/b/e/-original-imagsaxmzncmxghn.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1298
  },
  {
    "product_category": "watch",
    "product_id": "46",
    "product_title": "Hamilton Khaki Field Automatic",
    "product_subtitle": "Military-inspired timepiece with rugged charm",
    "product_description": "Embrace rugged charm with the Hamilton Khaki Field Automatic. Inspired by military watches, this timepiece features a stainless steel case, sapphire crystal, and automatic movement for reliable performance in any situation.",
    "product_price": 799,
    "product_mrp": 899,
    "product_size": "38mm",
    "product_brand": "Hamilton",
    "product_rating": 4.6,
    "product_offer": "11% off",
    "product_discount": 100,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/jxp08sw0/watch/p/h/q/233wdtg-timewear-original-imafg3hmqgxq4r8k.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/jxp08sw0/watch/p/h/q/233wdtg-timewear-original-imafg3hmqgxq4r8k.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/jxp08sw0/watch/p/h/q/233wdtg-timewear-original-imafg3hmqgxq4r8k.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/jxtakcw0/watch/f/n/2/235wdtg-timewear-original-imafg3h8rg5arkyf.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/g/0/6/-original-imaghny6bxfmgmqz.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 897
  },
  {
    "product_category": "watch",
    "product_id": "47",
    "product_title": "Longines Master Collection",
    "product_subtitle": "Swiss elegance with contemporary flair",
    "product_description": "Discover Swiss elegance with contemporary flair in the Longines Master Collection. Featuring a stainless steel case, sapphire crystal, and automatic movement, this watch exudes sophistication.",
    "product_price": 1999,
    "product_mrp": 2199,
    "product_size": "40mm",
    "product_brand": "Longines",
    "product_rating": 4.8,
    "product_offer": "9% off",
    "product_discount": 200,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/kdoup3k0-0/watch/a/o/y/3240sm03-fastrack-original-imafuj94mdngddcy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kdoup3k0-0/watch/z/a/l/3240sm03-fastrack-original-imafuj94ggervpaz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/a/f/-original-imagz4wvhbkrvfym.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kdoup3k0-0/watch/2/t/l/3240sm03-fastrack-original-imafuj94jsyznwtw.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kdoup3k0-0/watch/2/t/l/3240sm03-fastrack-original-imafuj94jsyznwtw.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 734
  },
  {
    "product_category": "watch",
    "product_id": "48",
    "product_title": "Casio G-Shock DW5600E",
    "product_subtitle": "Rugged digital watch for outdoor enthusiasts",
    "product_description": "Conquer the outdoors with the Casio G-Shock DW5600E. Built to withstand harsh conditions, this rugged digital watch features shock resistance, 200-meter water resistance, and iconic G-Shock durability.",
    "product_price": 79,
    "product_mrp": 99,
    "product_size": "43mm",
    "product_brand": "Casio",
    "product_rating": 4.7,
    "product_offer": "20% off",
    "product_discount": 20,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/n/m/g/1-1540102-hugo-women-original-imaghhtdbguyzfar.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/f/l/p/1-1540102-hugo-women-original-imaghhtdfy6zzs4v.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/f/l/p/1-1540102-hugo-women-original-imaghhtdfy6zzs4v.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/u/9/o/1-1540102-hugo-women-original-imaghhtdqtdkrahs.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/u/9/o/1-1540102-hugo-women-original-imaghhtdqtdkrahs.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 1001
  },
  {
    "product_category": "watch",
    "product_id": "49",
    "product_title": "Breitling Navitimer",
    "product_subtitle": "Legendary pilot's watch for aviation enthusiasts",
    "product_description": "Experience the legend of aviation with the Breitling Navitimer. Designed for pilots, this iconic watch features a stainless steel case, slide rule bezel, and chronograph function for precision navigation.",
    "product_price": 5499,
    "product_mrp": 5999,
    "product_size": "41mm",
    "product_brand": "Breitling",
    "product_rating": 4.9,
    "product_offer": "8% off",
    "product_discount": 500,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/w/o/l/1-316wdtg-timewear-men-original-imagk3jrvkn8f3ae.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/h/w/q/1-316wdtg-timewear-men-original-imagjahduxbdfhbf.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/b/d/e/1-316wdtg-timewear-men-original-imagk3jr9wtrpmhz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/p/a/1-309bdtg-timewear-men-original-imagj8fytuq3fzvz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/h/2/q/1-316wdtg-timewear-men-original-imagk3jrag9dseah.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 888
  },
  {
    "product_category": "watch",
    "product_id": "50",
    "product_title": "IWC Portugieser Chronograph",
    "product_subtitle": "Elegant chronograph for discerning gentlemen",
    "product_description": "Elevate your style with the IWC Portugieser Chronograph. Featuring a stainless steel case, sapphire crystal, and automatic movement, this elegant watch exudes sophistication and refinement.",
    "product_price": 8999,
    "product_mrp": 9999,
    "product_size": "41mm",
    "product_brand": "IWC",
    "product_rating": 4.8,
    "product_offer": "10% off",
    "product_discount": 1000,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/s/7/6/1-th1710494-tommy-hilfiger-men-original-imaghhzga2jzzcet.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/x/6/1-th1710494-tommy-hilfiger-men-original-imaghhzgqyf5eugq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/9/8/v/-original-imagp8nzctutnzkh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/7/l/b/1-th1710494-tommy-hilfiger-men-original-imaghhzgzwwfntyk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/x/6/1-th1710494-tommy-hilfiger-men-original-imaghhzgqyf5eugq.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 754
  },
  {
    "product_category": "watch",
    "product_id": "51",
    "product_title": "Cartier Santos",
    "product_subtitle": "Elegance and sophistication",
    "product_description": "Embrace elegance and sophistication with the Cartier Santos. Featuring a stainless steel case, sapphire crystal, and iconic square bezel, this watch blends classic design with modern refinement.",
    "product_price": 5500,
    "product_mrp": 5999,
    "product_size": "One Size",
    "product_brand": "Cartier",
    "product_rating": 4.9,
    "product_offer": "8% off",
    "product_discount": 499,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/kruyw7k0/watch/g/j/r/a1486-casio-original-imag5jsqhfk8jrey.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kruyw7k0/watch/2/w/r/a1486-casio-original-imag5jsq5b9zye6x.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/h/9/l/-original-imagrgwx2bn8gqna.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/kruyw7k0/watch/6/e/j/a1486-casio-original-imag5jsqceygqa2k.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/l01blow0/watch/d/m/x/-original-imagbwyy7fuqc4qx.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 632
  },
  {
    "product_category": "watch",
    "product_id": "52",
    "product_title": "Seiko 5 Sports",
    "product_subtitle": "Versatile and reliable",
    "product_description": "Discover versatility and reliability in the Seiko 5 Sports. Featuring a stainless steel case, Hardlex crystal, and automatic movement, this watch offers exceptional value and performance.",
    "product_price": 299,
    "product_mrp": 349,
    "product_size": "One Size",
    "product_brand": "Seiko",
    "product_rating": 4.6,
    "product_offer": "14% off",
    "product_discount": 50,
    "product_images": [
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/z/e/c/1-srpj45k1-seiko-men-original-imags23hme63uvkh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/x/e/q/1-srpj45k1-seiko-men-original-imags23hnugx6af6.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/y/f/n/1-srpj45k1-seiko-men-original-imags23hhdamjbg4.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/f/b/9/1-srpj45k1-seiko-men-original-imags23hvjbftt5t.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/u/p/7/1-srpj45k1-seiko-men-original-imags23htufnv9dy.jpeg?q=70&crop=false"
    ],
    "product_number_of_review": 182
  }

]  
